const TIME_CACHE_DEFAULT = 60;

const KEY_TOTAL_BALANCE = 'totalBalance';

const KEY_ACCESS_TOKEN = 'accessToken';

const ONE_DAY_IN_SECONDS = 24 * 60 * 60 * 1000;

const DATE_NUMBER_DIFFERENCE = 1;

const KEY_LIST_PAYMENTS = 'listPayments';

module.exports = {
  KEY_ACCESS_TOKEN,
  KEY_LIST_PAYMENTS,
  KEY_TOTAL_BALANCE,
  TIME_CACHE_DEFAULT,
  ONE_DAY_IN_SECONDS,
  DATE_NUMBER_DIFFERENCE,
};
